# Generated by Django 3.1.3 on 2021-01-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('EN_site_name', models.CharField(blank=True, max_length=25, null=True)),
                ('EN_proj_num', models.DecimalField(decimal_places=2, max_digits=9, primary_key=True, serialize=False)),
                ('mech_WorkOrder_num', models.DecimalField(decimal_places=0, default=1, max_digits=9)),
                ('elec_WorkOrder_num', models.DecimalField(decimal_places=0, default=1, max_digits=9)),
                ('revision_Num', models.CharField(blank=True, max_length=1, null=True)),
                ('revision_Type', models.CharField(blank=True, max_length=25, null=True)),
                ('prepared_By', models.CharField(blank=True, max_length=3, null=True)),
                ('reviewed_By', models.CharField(blank=True, max_length=3, null=True)),
                ('approved_By', models.CharField(blank=True, max_length=3, null=True)),
                ('submittal_date', models.CharField(blank=True, max_length=12, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('County', models.CharField(blank=True, max_length=50, null=True)),
                ('Section', models.CharField(blank=True, max_length=4, null=True)),
                ('Township', models.CharField(blank=True, max_length=4, null=True)),
                ('Range', models.CharField(blank=True, max_length=4, null=True)),
                ('Division', models.CharField(blank=True, max_length=50, null=True)),
                ('Lattitude', models.DecimalField(decimal_places=6, default=100.0, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, default=100.0, max_digits=9)),
                ('Scope', models.CharField(blank=True, max_length=300, null=True)),
                ('ScopeBullet_1', models.CharField(blank=True, max_length=300, null=True)),
                ('ScopeBullet_2', models.CharField(blank=True, max_length=300, null=True)),
                ('ScopeBullet_3', models.CharField(blank=True, max_length=300, null=True)),
                ('ScopeBullet_4', models.CharField(blank=True, max_length=300, null=True)),
                ('ScopeBullet_5', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valve_Type', models.CharField(default='Ball', max_length=9)),
                ('Valve_Tag1', models.CharField(max_length=9)),
                ('Valve_Class', models.CharField(default='ANSI 600', max_length=9)),
                ('Valve_Size1', models.CharField(max_length=5)),
                ('Valve_Man1', models.CharField(max_length=25)),
                ('Valve_Model1', models.CharField(max_length=25)),
                ('Valve_Serial1', models.CharField(max_length=25)),
                ('Valve_Max_Diff1', models.CharField(max_length=25)),
                ('Valve_Actuator1', models.CharField(max_length=50)),
                ('Valve_Project_num', models.ForeignKey(default=1.01, on_delete=django.db.models.deletion.CASCADE, to='Homepage.project')),
            ],
        ),
    ]
