# Generated by Django 3.1.3 on 2021-01-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_actuator'),
    ]

    operations = [
        migrations.AddField(
            model_name='valves',
            name='Valve_Max_Rlf1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='valves',
            name='Valve_Max_Diff1',
            field=models.IntegerField(),
        ),
    ]
