# Generated by Django 3.1.3 on 2021-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_auto_20210109_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torque_table',
            name='Torque_Cnst2',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
