# Generated by Django 3.1.3 on 2021-01-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_auto_20210109_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valves',
            name='Valve_Max_Rlf1',
        ),
        migrations.AddField(
            model_name='valves',
            name='Valve_SafetyFactor',
            field=models.IntegerField(default=1.5),
        ),
    ]
