# Generated by Django 3.1.3 on 2021-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_auto_20210110_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='torque_table',
            name='Valve_Run_Torque',
            field=models.IntegerField(default=100),
        ),
    ]
