# Generated by Django 3.1.3 on 2021-01-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_auto_20210112_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valves',
            name='Valve_Break_Torque_SF',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='valves',
            name='Valve_Run_Torque_SF',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
