# Generated by Django 3.1.3 on 2021-01-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_auto_20210116_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valves',
            name='Valve_Project_num',
            field=models.ForeignKey(default=1.01, on_delete=django.db.models.deletion.CASCADE, to='Homepage.project'),
        ),
    ]
