# Generated by Django 3.1.3 on 2021-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_auto_20210116_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_County_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=50)),
                ('County', models.CharField(max_length=75)),
                ('Low_Temp', models.IntegerField()),
                ('High_Temp', models.IntegerField()),
            ],
        ),
    ]
