# Generated by Django 3.1.3 on 2021-01-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_city_county_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='valves',
            name='Valve_High_Temp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valves',
            name='Valve_Low_Temp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
