# Generated by Django 3.1.3 on 2021-01-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0013_auto_20210123_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valves',
            name='Valve_High_Temp',
        ),
        migrations.RemoveField(
            model_name='valves',
            name='Valve_Low_Temp',
        ),
        migrations.AddField(
            model_name='project',
            name='Site_High_Temp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Site_Low_Temp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
